### ISSUE TITLE
Taller de Flutter

### ISSUE THREAD

**Issue by spenicheg** [ISCOUTB/DG-Financiero#1]

**Comment by criss132** [comment]
ok

**Comment by criss132** [comment]
![evidencia2](https://github.com/user-attachments/assets/fe9404ab-08ff-4ca8-966e-c78bb490488a)
![evidencias](https://github.com/user-attachments/assets/8d0ed571-562f-4091-8f0c-0692f9367b86)
Despues de diversos tutoriales para instalación y uso del flutter se instaló correctamente aunque se produjeron algunos inconvenientes con el sdk manager y algunos errores al momento de confirmar su ruta en el path

**Comment by criss132** [comment]
![Image](https://github.com/user-attachments/assets/7755165d-9218-4563-ae17-ef7f78c1382f)

**Comment by criss132** [comment]
![Image](https://github.com/user-attachments/assets/44ccb3ac-ea0c-4b58-be1e-ee2c24b1183e)
