### ISSUE TITLE
Construccion de Backend

### ISSUE THREAD

**Issue by spenicheg** [ISCOUTB/DG-Financiero#2]
Definir el uso de Flask o FastAPI

**Comment by criss132** [comment]
Facilidad de uso y simplicidad:

Flask: Es conocido por su simplicidad y flexibilidad. Si tienes experiencia previa con Flask o buscas una solución mínima para tu aplicación web, Flask podría ser más adecuado. Es excelente para proyectos pequeños y medianos, con una gran comunidad y soporte.
FastAPI: Está diseñado para ser rápido y eficiente, con soporte nativo para solicitudes asincrónicas y un enfoque en la creación de APIs RESTful. Si tu aplicación puede beneficiarse de la velocidad y deseas aprovechar características como la validación automática de datos basada en anotaciones de tipos, FastAPI sería ideal.
Rendimiento:

FastAPI: Es más rápido que Flask debido a su enfoque en la programación asíncrona y su uso de Starlette como base. Si esperas una alta carga de usuarios o transacciones, FastAPI ofrecerá un rendimiento superior.
Flask: Aunque no es tan rápido como FastAPI, sigue siendo suficientemente eficiente para muchas aplicaciones, especialmente si no necesitas manejar muchas solicitudes simultáneamente.
Escalabilidad:

FastAPI: Su arquitectura asincrónica permite manejar más solicitudes concurrentes, lo que puede ser importante si planeas escalar el sistema rápidamente.
Flask: Aunque puede escalar, no tiene soporte nativo para la asincronía, lo que puede limitar su rendimiento en entornos de alta carga.
Desarrollo rápido y productividad:

Flask: Es muy flexible y puedes agregar solo los componentes que necesites, lo que puede hacer que el desarrollo inicial sea más rápido si prefieres personalizar cada aspecto.
FastAPI: Proporciona una validación automática de datos y documentación interactiva para las APIs (con Swagger y Redoc), lo que puede acelerar el desarrollo y las pruebas.
Compatibilidad y soporte:

Ambos funcionan bien en entornos Windows y Android, pero FastAPI está más optimizado para construir APIs robustas y modernas.

En base a esta información opto por usar FastAPI ya sea para la adquisición de experiencia en la misma y su versatilidad al momento del desarrollo y pruebas de la API.

**Comment by YoePerezJimenez** [comment]
ok

**Comment by YoePerezJimenez** [comment]
Python es un lenguaje de programacion sencillo y con una gran cantidad de frameworks. Entre esos frameworks modernos esta FastAPI el cual para backend es de alto rendimiento y por esto mismo ofrece las siguientes ventajas:
- FastAPI está diseñado para ser extremadamente rápido, crusial para el manejo de grandes volumenes de datos y cambios en tiempo real.
- Permite manejar multiples solicitudes concurrentes de manera eficiente sin bloquear el servidor, esto mejora la capacidad de respuesta de las aplicaciones.
- Genera automáticamente documentación interactiva de la API (Swagger UI y ReDoc) a partir de los esquemas de Pydantic, lo que facilita el desarrollo y prueba de la API.
- La sintaxis de FastAPI es clara y declarativa, lo que acelera el desarrollo al reducir la cantidad de código repetitivo necesario para definir rutas y manejar solicitudes.
- Al usar anotaciones de tipo de Python, el código es más fácil de leer y mantener. Estas anotaciones también facilitan la integración con editores de código y herramientas de análisis estático.

Por ende me parece FastAPI buen framework para la construcción del backend de la aplicación.

**Comment by Alejo234x** [comment]
Tanto Flask como FastAPI son frameworks de desarrollo web en Python, ampliamente utilizados para crear aplicaciones financieras debido a su flexibilidad, rendimiento y facilidad para integrar diversas funcionalidades.

Flask:
Flask es un microframework que proporciona herramientas básicas para desarrollar aplicaciones web. Es minimalista, lo que lo hace flexible y fácil de extender mediante plugins. 

Autenticación y seguridad: Esto es crucial en aplicaciones financieras para garantizar que las transacciones sean seguras y solo accesibles para usuarios autenticados.


Casos:
Gestión de cuentas: Flask maneja las solicitudes de los usuarios para consultar sus cuentas, ver balances y estados financieros.

Ventajas de usar Flask:
Flexibilidad: Flask es muy adaptable y puede ajustarse a diferentes necesidades específicas de una aplicación financiera.
Simplicidad: Al ser ligero, Flask permite un control detallado sobre los componentes de la aplicación sin añadir complejidad innecesaria.
Escalabilidad: Aunque Flask es un microframework, se puede extender fácilmente mediante módulos externos para escalar la aplicación a medida que crece.

Por lo tamto la opcion a utilizar es flask
