### ISSUE TITLE
Definir Wireframes de toda la aplicacion

### ISSUE THREAD

**Issue by spenicheg** [ISCOUTB/DG-Financiero#3]

**Comment by criss132** [comment]
1. Pantalla de Inicio / Dashboard
Objetivo: Mostrar un resumen rápido de los ingresos, gastos, y progreso hacia los objetivos financieros.

Componentes:

Barra superior: Nombre de la aplicación, icono de perfil de usuario, y botón de menú.
Resumen de saldos:
Total de ingresos y gastos del mes.
Dinero restante.
Progreso hacia objetivos: Gráfica de progreso para cada objetivo financiero (barra de progreso o gráfico de anillos).
Gráfica de gastos: Gráfico de barras o circular que muestra la distribución de gastos por categoría (alimentación, transporte, etc.).
Botón de acceso rápido: Botón para agregar una nueva entrada de gasto o ingreso.

**Comment by criss132** [comment]
2. Pantalla de Ingreso de Datos (Ingresos/Gastos)
Objetivo: Permitir al usuario registrar un ingreso o gasto.

Componentes:

Título: “Registrar Gasto” o “Registrar Ingreso” (dependiendo del contexto).
Formulario de entrada:
Campo Monto (input numérico).
Campo Descripción (input de texto corto).
Campo Fecha (input de calendario).
Campo Categoría (desplegable con opciones predefinidas: Alimentación, Transporte, Ocio, etc.).
Botón Guardar.
Botón Cancelar para regresar al dashboard.

**Comment by criss132** [comment]
3. Pantalla de Objetivos Financieros
Objetivo: Permitir al usuario establecer y gestionar objetivos financieros.

Componentes:

Título: “Objetivos Financieros”.
Lista de Objetivos:
Cada objetivo debe mostrar el monto total, el progreso actual (barra de progreso) y una opción para editar o eliminar.
Botón Agregar Objetivo:
Formulario emergente con campos:
Nombre del objetivo.
Monto deseado.
Fecha límite (opcional).
Botón Guardar y Botón Cancelar.

**Comment by criss132** [comment]
4. Pantalla de Reportes
Objetivo: Generar informes de ingresos y gastos de manera visual.

Componentes:

Título: “Informe Mensual de Finanzas”.
Selector de Fecha: Seleccionar el mes o rango de fechas a analizar.
Gráfica de Ingresos y Gastos:
Gráfico de barras que muestra la evolución de ingresos y gastos a lo largo del tiempo (día/mes).
Gráfica Circular por Categoría: Distribución de gastos por categorías.
Botón Exportar Informe (opción para descargar el reporte en formato PDF o CSV).

**Comment by criss132** [comment]
5. Pantalla de Alertas de Presupuesto
Objetivo: Mostrar alertas cuando el usuario se acerca a exceder su presupuesto en una categoría.

Componentes:

Lista de Alertas:
Mensajes que indican si un gasto está cerca de exceder el límite de una categoría.
Cada alerta incluirá el monto gastado, el límite, y un botón para ver más detalles.
Opciones de Configuración: Posibilidad de modificar los límites de gasto por categoría.
Botón Volver al Dashboard.

**Comment by criss132** [comment]
6. Pantalla de Configuración
Objetivo: Permitir la configuración de la cuenta del usuario y personalización de categorías de gastos.

Componentes:

Título: “Configuración de Usuario”.
Formulario de Configuración:
Editar Información del Usuario (nombre, correo, etc.).
Opciones de Moneda: Seleccionar la moneda local para los registros financieros.
Gestión de Categorías:
Añadir nuevas categorías de gastos.
Editar o eliminar categorías existentes.
Botón Guardar Cambios.
Botón Volver al Dashboard.

**Comment by criss132** [comment]
7. Pantalla de Login / Registro
Objetivo: Permitir al usuario iniciar sesión o registrarse.

Componentes:

Título: “Iniciar Sesión” o “Crear Cuenta”.
Formulario de Login:
Campo de Correo Electrónico.
Campo de Contraseña.
Botón de Iniciar Sesión.
Opción de Recuperar Contraseña.
Formulario de Registro (en caso de ser un nuevo usuario):
Nombre, correo electrónico, y contraseña.
Botón Registrar.

**Comment by YoePerezJimenez** [comment]
8. Pantalla de recuperación de cuenta 
 objetivo: Permitir a los usuarios recuperar o restablecer su contraseña en caso de olvidarla.

componentes:

Título: “Recuperar Contraseña”.
Campo de Correo Electrónico: Para enviar el enlace de recuperación.
Botón de Enviar: Envía el enlace de recuperación al correo electrónico ingresado.
Instrucciones: Mensaje sobre el proceso de recuperación.
botón de "enviar" ó tambien puede llamarse "enviar enlace de recuperación".
botón de "volver al login"
botón de "cancelar"

**Comment by Alejo234x** [comment]
Componentes:

1. Pantalla de Inicio:

Pantalla de Inicio: Campos de login y registro seguros.

   - Resumen financiero, como saldo y ingresos.
   - Gráficos de balance.
   - Accesos rápidos.

2. Pantalla de gastos:
   - Historial de gastos.
   - Filtros por tipo o fecha.

3. Pantalla de Configuración:
   - Datos personales.
   - Preferencias de notificación y seguridad.

4. Reportes Financieros
Permitir al usuario generar reportes detallados de sus finanzas en periodos específicos (mensuales, trimestrales, anuales).

Datos personales: Formulario para actualizar nombre, correo electrónico, teléfono.

Seguridad: Configuraciones para cambiar la contraseña, activar la autenticación.

Notificación: Opciones para activar y desactivar alertas.

**Comment by YoePerezJimenez** [comment]
9. Pantalla de registro
 Objetivo: registro de cuenta a gestionar las finanzas.

 Intruciones: sobre como registrarse para despues ingresar a la app.

Titulo: "Regístrate" ó tambien se le puede agregar el nombre de la app 
botones para: crear cuenta, iniciar sesión, boton de captar terminos y condiciones,

**Comment by criss132** [comment]
![Interfaz web](https://github.com/user-attachments/assets/00e0fc51-1431-4f61-9acf-ff3a46afea8e)
[Interfaz web.pdf](https://github.com/user-attachments/files/17191748/Interfaz.web.pdf)
